//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by NAPO.RC
//
#define IDI_ICON1                       101
#define IDC_CURSOR1                     102
#define IDD_DIALOG1                     103
#define IDR_MENU1                       104
#define IDI_ICON2                       105
#define IDC_CHECK1                      1000
#define IDC_CHECK2                      1001
#define IDC_CHECK3                      1002
#define IDM_POLI                        40002
#define IDM_LINE                        40003
#define IDM_FACE                        40004
#define IDM_KASUMI                      40005
#define IDM_RENB                        40006
#define IDM_HELP                        40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
